FROM openjdk:18-alpine
LABEL maintainer="item987"
COPY /target/legacy-application-0.0.1-SNAPSHOT.jar legacy-application-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/legacy-application-0.0.1-SNAPSHOT.jar"]